/**
 * meta.tool-creator — Template-based tool creator for SUDO-AI.
 *
 * Unlike meta.skill-creator (which uses LLM to generate code), this tool
 * creates tools from pre-built TypeScript templates with specific parameters.
 * Faster, more reliable, zero token cost.
 *
 * Actions:
 *   create-file-tool      — Tool that reads/writes/transforms a specific file type
 *   create-api-tool       — Tool that calls an external HTTP API
 *   create-shell-tool     — Tool that runs a specific shell command safely
 *   create-db-tool        — Tool that queries/updates a SQLite database
 *   create-composite-tool — Tool that chains multiple existing tools
 *   list-custom           — List all custom-created tools
 *   test-tool             — Dry-run a custom tool with test params
 */

import type { ToolDefinition, ToolContext, ToolResult } from '../../types.js';
import { createLogger } from '../../../shared/logger.js';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const logger = createLogger('meta.tool-creator');

const CUSTOM_DIR = path.resolve('src/core/tools/builtin/custom');

// ---------------------------------------------------------------------------
// Name helpers
// ---------------------------------------------------------------------------

const NAME_PATTERN = /^[a-z][a-z0-9-]*\.[a-z][a-z0-9-]*$/;

/** Convert dot-namespaced name to a valid JS variable: "custom.my-tool" → "custom_my_tool" */
function toVarName(name: string): string {
  return name.replace(/[.-]/g, '_');
}

/** Convert dot-namespaced name to a filename: "custom.my-tool" → "custom-my-tool.ts" */
function toFileName(name: string): string {
  return `${name.replace(/\./g, '-')}.ts`;
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validateToolName(toolName: string | undefined): ToolResult | null {
  if (!toolName?.trim()) {
    return { success: false, output: 'toolName is required.' };
  }
  if (!NAME_PATTERN.test(toolName)) {
    return {
      success: false,
      output: `toolName must match pattern <category>.<action> using lowercase letters, numbers, and hyphens. Got: "${toolName}"`,
    };
  }
  return null;
}

// ---------------------------------------------------------------------------
// Template generators
// ---------------------------------------------------------------------------

function generateFileToolCode(
  toolName: string,
  description: string,
  targetPath: string,
  operations: string[],
): string {
  const varName = toVarName(toolName);
  const ops = JSON.stringify(operations);

  return `// Auto-generated by meta.tool-creator
import type { ToolDefinition, ToolContext, ToolResult } from '../../types.js';
import { readFileSync, writeFileSync, appendFileSync, unlinkSync, existsSync } from 'node:fs';
import { createLogger } from '../../../shared/logger.js';
import path from 'node:path';

const logger = createLogger('${toolName}');

export const ${varName}Tool: ToolDefinition = {
  name: '${toolName}',
  description: ${JSON.stringify(description)},
  category: 'meta' as const,
  timeout: 15_000,
  requiresConfirmation: true,
  parameters: {
    action: { type: 'string', required: true, description: 'Operation to perform.', enum: ${ops} },
    content: { type: 'string', description: 'Content for write/append operations.' },
  },
  async execute(params: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
    const action = params['action'] as string;
    const content = params['content'] as string | undefined;
    const filePath = path.resolve(${JSON.stringify(targetPath)});
    logger.info({ session: ctx.sessionId, action, filePath }, '${toolName} invoked');

    try {
      switch (action) {
        case 'read': {
          if (!existsSync(filePath)) return { success: false, output: \`File not found: \${filePath}\` };
          const data = readFileSync(filePath, 'utf8');
          return { success: true, output: data, artifacts: [{ path: filePath, action: 'read' }] };
        }
        case 'write': {
          if (!content) return { success: false, output: 'content is required for write.' };
          writeFileSync(filePath, content, 'utf8');
          return { success: true, output: \`Written \${content.length} chars to \${filePath}\`, artifacts: [{ path: filePath, action: 'created' }] };
        }
        case 'append': {
          if (!content) return { success: false, output: 'content is required for append.' };
          appendFileSync(filePath, content, 'utf8');
          return { success: true, output: \`Appended \${content.length} chars to \${filePath}\`, artifacts: [{ path: filePath, action: 'modified' }] };
        }
        case 'delete': {
          if (!existsSync(filePath)) return { success: false, output: \`File not found: \${filePath}\` };
          unlinkSync(filePath);
          return { success: true, output: \`Deleted \${filePath}\`, artifacts: [{ path: filePath, action: 'deleted' }] };
        }
        default:
          return { success: false, output: \`Unknown action: \${action}\` };
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error({ err: msg }, '${toolName} error');
      return { success: false, output: \`Error: \${msg}\` };
    }
  },
};
`;
}

function generateApiToolCode(
  toolName: string,
  description: string,
  baseUrl: string,
  method: string,
  headers: Record<string, string>,
  bodyTemplate: string,
): string {
  const varName = toVarName(toolName);

  // Transform headers so values referencing env vars use process.env at runtime
  const headerEntries = Object.entries(headers).map(([k, v]) => {
    // If the value looks like an env var reference (e.g. "$MY_API_KEY"), resolve at runtime
    if (v.startsWith('$')) {
      return `    '${k}': process.env['${v.slice(1)}'] ?? ''`;
    }
    return `    '${k}': ${JSON.stringify(v)}`;
  });
  const headersCode = headerEntries.length > 0
    ? `{\n${headerEntries.join(',\n')}\n  }`
    : '{}';

  return `// Auto-generated by meta.tool-creator
import type { ToolDefinition, ToolContext, ToolResult } from '../../types.js';
import { createLogger } from '../../../shared/logger.js';

const logger = createLogger('${toolName}');

export const ${varName}Tool: ToolDefinition = {
  name: '${toolName}',
  description: ${JSON.stringify(description)},
  category: 'meta' as const,
  timeout: 30_000,
  requiresConfirmation: true,
  parameters: {
    body: { type: 'object', description: 'Request body (JSON).', properties: {} },
    pathSuffix: { type: 'string', description: 'Optional path appended to the base URL.' },
    queryParams: { type: 'object', description: 'URL query parameters.', properties: {} },
  },
  async execute(params: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
    const body = params['body'] as Record<string, unknown> | undefined;
    const pathSuffix = (params['pathSuffix'] as string | undefined) ?? '';
    const queryParams = params['queryParams'] as Record<string, string> | undefined;
    logger.info({ session: ctx.sessionId }, '${toolName} invoked');

    try {
      let url = ${JSON.stringify(baseUrl)} + pathSuffix;
      if (queryParams && Object.keys(queryParams).length > 0) {
        const qs = new URLSearchParams(queryParams).toString();
        url += (url.includes('?') ? '&' : '?') + qs;
      }

      const headers: Record<string, string> = ${headersCode};

      const method = ${JSON.stringify(method.toUpperCase())};
      const hasBody = method !== 'GET' && method !== 'HEAD' && body;

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
          ...headers,
        },
        ...(hasBody ? { body: JSON.stringify(body) } : {}),
        signal: ctx.signal,
      });

      const text = await response.text();
      let data: unknown;
      try { data = JSON.parse(text); } catch { data = text; }

      if (!response.ok) {
        return { success: false, output: \`HTTP \${response.status}: \${text.slice(0, 500)}\`, data };
      }
      return { success: true, output: typeof data === 'string' ? data.slice(0, 2000) : JSON.stringify(data, null, 2).slice(0, 2000), data };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error({ err: msg }, '${toolName} error');
      return { success: false, output: \`Error: \${msg}\` };
    }
  },
};
`;
}

function generateShellToolCode(
  toolName: string,
  description: string,
  command: string,
  allowedArgs: string[],
  timeout: number,
): string {
  const varName = toVarName(toolName);

  return `// Auto-generated by meta.tool-creator
import type { ToolDefinition, ToolContext, ToolResult } from '../../types.js';
import { createLogger } from '../../../shared/logger.js';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);
const logger = createLogger('${toolName}');

const ALLOWED_ARGS: string[] = ${JSON.stringify(allowedArgs)};
const TIMEOUT_MS = ${timeout};

export const ${varName}Tool: ToolDefinition = {
  name: '${toolName}',
  description: ${JSON.stringify(description)},
  category: 'meta' as const,
  timeout: ${timeout + 5000},
  requiresConfirmation: true,
  parameters: {
    args: { type: 'array', description: 'Arguments to pass to the command. Must be from the allowed list.', items: { type: 'string', description: 'Argument value.' } },
  },
  async execute(params: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
    const args = (params['args'] as string[] | undefined) ?? [];
    logger.info({ session: ctx.sessionId, args }, '${toolName} invoked');

    try {
      // Validate args against allowlist
      if (ALLOWED_ARGS.length > 0) {
        for (const arg of args) {
          if (!ALLOWED_ARGS.includes(arg)) {
            return { success: false, output: \`Argument not allowed: "\${arg}". Allowed: \${ALLOWED_ARGS.join(', ')}\` };
          }
        }
      }

      const { stdout, stderr } = await execFileAsync(${JSON.stringify(command)}, args, {
        timeout: TIMEOUT_MS,
        cwd: ctx.workingDir,
        env: process.env,
      });

      const output = (stdout + (stderr ? \`\\nSTDERR: \${stderr}\` : '')).trim();
      return { success: true, output: output.slice(0, 5000) };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error({ err: msg }, '${toolName} error');
      return { success: false, output: \`Error: \${msg}\` };
    }
  },
};
`;
}

function generateDbToolCode(
  toolName: string,
  description: string,
  dbPath: string,
  queries: Array<{ name: string; sql: string }>,
): string {
  const varName = toVarName(toolName);
  const queryEnum = queries.map(q => q.name);
  const queryMap = queries.reduce<Record<string, string>>((acc, q) => {
    acc[q.name] = q.sql;
    return acc;
  }, {});

  return `// Auto-generated by meta.tool-creator
import type { ToolDefinition, ToolContext, ToolResult } from '../../types.js';
import { createLogger } from '../../../shared/logger.js';
import Database from 'better-sqlite3';
import path from 'node:path';

const logger = createLogger('${toolName}');

const DB_PATH = path.resolve(${JSON.stringify(dbPath)});
const QUERIES: Record<string, string> = ${JSON.stringify(queryMap, null, 2)};

export const ${varName}Tool: ToolDefinition = {
  name: '${toolName}',
  description: ${JSON.stringify(description)},
  category: 'meta' as const,
  timeout: 15_000,
  requiresConfirmation: true,
  parameters: {
    query: { type: 'string', required: true, description: 'Named query to execute.', enum: ${JSON.stringify(queryEnum)} },
    params: { type: 'object', description: 'Named parameters for the SQL query (e.g. { ":name": "value" }).', properties: {} },
  },
  async execute(params: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
    const queryName = params['query'] as string;
    const queryParams = (params['params'] as Record<string, unknown> | undefined) ?? {};
    logger.info({ session: ctx.sessionId, query: queryName }, '${toolName} invoked');

    try {
      const sql = QUERIES[queryName];
      if (!sql) return { success: false, output: \`Unknown query: \${queryName}. Available: \${Object.keys(QUERIES).join(', ')}\` };

      const db = new Database(DB_PATH, { readonly: sql.trim().toUpperCase().startsWith('SELECT') });
      try {
        const isSelect = sql.trim().toUpperCase().startsWith('SELECT');
        if (isSelect) {
          const rows = db.prepare(sql).all(queryParams);
          return { success: true, output: JSON.stringify(rows, null, 2).slice(0, 5000), data: rows };
        } else {
          const result = db.prepare(sql).run(queryParams);
          return { success: true, output: \`Rows affected: \${result.changes}\`, data: { changes: result.changes, lastInsertRowid: result.lastInsertRowid } };
        }
      } finally {
        db.close();
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error({ err: msg }, '${toolName} error');
      return { success: false, output: \`Error: \${msg}\` };
    }
  },
};
`;
}

function generateCompositeToolCode(
  toolName: string,
  description: string,
  steps: Array<{ tool: string; params: Record<string, unknown> }>,
): string {
  const varName = toVarName(toolName);

  return `// Auto-generated by meta.tool-creator
import type { ToolDefinition, ToolContext, ToolResult } from '../../types.js';
import { createLogger } from '../../../shared/logger.js';

const logger = createLogger('${toolName}');

/**
 * Composite tool pipeline — chains multiple tool calls sequentially.
 * The execution plan is returned for the agent loop to run.
 */
const STEPS: Array<{ tool: string; params: Record<string, unknown> }> = ${JSON.stringify(steps, null, 2)};

export const ${varName}Tool: ToolDefinition = {
  name: '${toolName}',
  description: ${JSON.stringify(description)},
  category: 'meta' as const,
  timeout: 60_000,
  requiresConfirmation: true,
  parameters: {
    overrides: { type: 'object', description: 'Per-step param overrides keyed by 0-based index (e.g. { "0": { "extra": "val" } }).', properties: {} },
    dryRun: { type: 'boolean', description: 'If true, return the execution plan without running.', default: false },
  },
  async execute(params: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
    const overrides = (params['overrides'] as Record<string, Record<string, unknown>> | undefined) ?? {};
    const dryRun = (params['dryRun'] as boolean | undefined) ?? false;
    logger.info({ session: ctx.sessionId, steps: STEPS.length, dryRun }, '${toolName} invoked');

    const plan = STEPS.map((step, i) => ({
      step: i + 1,
      tool: step.tool,
      params: { ...step.params, ...(overrides[String(i)] ?? {}) },
    }));

    const planText = plan.map(s => \`Step \${s.step}: \${s.tool}(\${JSON.stringify(s.params)})\`).join('\\n');

    if (dryRun) {
      return { success: true, output: \`Composite tool plan (dry-run):\\n\${planText}\`, data: { plan } };
    }

    return {
      success: true,
      output: \`Composite tool execution plan (\${plan.length} steps):\\n\${planText}\\n\\nAgent: execute each step in order.\`,
      data: { plan },
    };
  },
};
`;
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

async function ensureCustomDir(): Promise<void> {
  if (!existsSync(CUSTOM_DIR)) {
    await mkdir(CUSTOM_DIR, { recursive: true });
  }
}

async function createFileTool(
  toolName: string,
  description: string,
  templateParams: Record<string, unknown>,
): Promise<ToolResult> {
  const targetPath = templateParams['targetPath'] as string | undefined;
  const operations = (templateParams['operations'] as string[] | undefined) ?? ['read', 'write', 'append', 'delete'];

  if (!targetPath?.trim()) {
    return { success: false, output: 'templateParams.targetPath is required for create-file-tool.' };
  }

  const validOps = ['read', 'write', 'append', 'delete'];
  for (const op of operations) {
    if (!validOps.includes(op)) {
      return { success: false, output: `Invalid operation: "${op}". Valid: ${validOps.join(', ')}` };
    }
  }

  await ensureCustomDir();
  const code = generateFileToolCode(toolName, description, targetPath, operations);
  const filePath = path.join(CUSTOM_DIR, toFileName(toolName));
  await writeFile(filePath, code, 'utf8');

  return {
    success: true,
    output: `File tool "${toolName}" created at ${filePath}\nOperations: ${operations.join(', ')}\nTarget: ${targetPath}`,
    data: { toolName, filePath, operations, targetPath },
    artifacts: [{ path: filePath, action: 'created' }],
  };
}

async function createApiTool(
  toolName: string,
  description: string,
  templateParams: Record<string, unknown>,
): Promise<ToolResult> {
  const baseUrl = templateParams['baseUrl'] as string | undefined;
  const method = (templateParams['method'] as string | undefined) ?? 'GET';
  const headers = (templateParams['headers'] as Record<string, string> | undefined) ?? {};
  const bodyTemplate = (templateParams['bodyTemplate'] as string | undefined) ?? '';

  if (!baseUrl?.trim()) {
    return { success: false, output: 'templateParams.baseUrl is required for create-api-tool.' };
  }

  // Safety: warn if headers contain literal secrets
  for (const [key, val] of Object.entries(headers)) {
    if (!val.startsWith('$') && /^(sk-|Bearer |token |key )/i.test(val)) {
      return {
        success: false,
        output: `Header "${key}" appears to contain a literal secret. Use an env var reference like "$MY_API_KEY" instead.`,
      };
    }
  }

  await ensureCustomDir();
  const code = generateApiToolCode(toolName, description, baseUrl, method, headers, bodyTemplate);
  const filePath = path.join(CUSTOM_DIR, toFileName(toolName));
  await writeFile(filePath, code, 'utf8');

  return {
    success: true,
    output: `API tool "${toolName}" created at ${filePath}\nEndpoint: ${method.toUpperCase()} ${baseUrl}\nHeaders pull from env vars at runtime.`,
    data: { toolName, filePath, baseUrl, method },
    artifacts: [{ path: filePath, action: 'created' }],
  };
}

async function createShellTool(
  toolName: string,
  description: string,
  templateParams: Record<string, unknown>,
): Promise<ToolResult> {
  const command = templateParams['command'] as string | undefined;
  const allowedArgs = (templateParams['allowedArgs'] as string[] | undefined) ?? [];
  const timeout = (templateParams['timeout'] as number | undefined) ?? 15_000;

  if (!command?.trim()) {
    return { success: false, output: 'templateParams.command is required for create-shell-tool.' };
  }

  // Safety: block dangerous base commands
  const dangerous = ['rm', 'dd', 'mkfs', 'format', 'shutdown', 'reboot', 'kill', 'killall'];
  const baseCmd = path.basename(command).toLowerCase();
  if (dangerous.includes(baseCmd)) {
    return { success: false, output: `Command "${command}" is blocked for safety. Dangerous base commands are not allowed.` };
  }

  await ensureCustomDir();
  const code = generateShellToolCode(toolName, description, command, allowedArgs, timeout);
  const filePath = path.join(CUSTOM_DIR, toFileName(toolName));
  await writeFile(filePath, code, 'utf8');

  return {
    success: true,
    output: `Shell tool "${toolName}" created at ${filePath}\nCommand: ${command}\nAllowed args: ${allowedArgs.length > 0 ? allowedArgs.join(', ') : '(any)'}`,
    data: { toolName, filePath, command, allowedArgs },
    artifacts: [{ path: filePath, action: 'created' }],
  };
}

async function createDbTool(
  toolName: string,
  description: string,
  templateParams: Record<string, unknown>,
): Promise<ToolResult> {
  const dbPath = templateParams['dbPath'] as string | undefined;
  const rawQueries = templateParams['queries'] as Array<{ name: string; sql: string }> | undefined;

  if (!dbPath?.trim()) {
    return { success: false, output: 'templateParams.dbPath is required for create-db-tool.' };
  }
  if (!rawQueries || rawQueries.length === 0) {
    return { success: false, output: 'templateParams.queries is required (array of { name, sql }).' };
  }

  for (const q of rawQueries) {
    if (!q.name || !q.sql) {
      return { success: false, output: 'Each query must have a "name" and "sql" field.' };
    }
  }

  await ensureCustomDir();
  const code = generateDbToolCode(toolName, description, dbPath, rawQueries);
  const filePath = path.join(CUSTOM_DIR, toFileName(toolName));
  await writeFile(filePath, code, 'utf8');

  return {
    success: true,
    output: `DB tool "${toolName}" created at ${filePath}\nDatabase: ${dbPath}\nQueries: ${rawQueries.map(q => q.name).join(', ')}`,
    data: { toolName, filePath, dbPath, queries: rawQueries.map(q => q.name) },
    artifacts: [{ path: filePath, action: 'created' }],
  };
}

async function createCompositeTool(
  toolName: string,
  description: string,
  templateParams: Record<string, unknown>,
): Promise<ToolResult> {
  const steps = templateParams['steps'] as Array<{ tool: string; params: Record<string, unknown> }> | undefined;

  if (!steps || steps.length === 0) {
    return { success: false, output: 'templateParams.steps is required (array of { tool, params }).' };
  }

  for (const step of steps) {
    if (!step.tool) {
      return { success: false, output: 'Each step must have a "tool" field.' };
    }
  }

  await ensureCustomDir();
  const code = generateCompositeToolCode(toolName, description, steps);
  const filePath = path.join(CUSTOM_DIR, toFileName(toolName));
  await writeFile(filePath, code, 'utf8');

  return {
    success: true,
    output: `Composite tool "${toolName}" created at ${filePath}\nSteps: ${steps.map(s => s.tool).join(' → ')}`,
    data: { toolName, filePath, steps: steps.map(s => s.tool) },
    artifacts: [{ path: filePath, action: 'created' }],
  };
}

function listCustomTools(): ToolResult {
  if (!existsSync(CUSTOM_DIR)) {
    return { success: true, output: 'No custom tools directory yet. Create a tool first.', data: [] };
  }

  const files = readdirSync(CUSTOM_DIR).filter(f => f.endsWith('.ts'));
  if (files.length === 0) {
    return { success: true, output: 'No custom tools found.', data: [] };
  }

  const tools = files.map(f => {
    const filePath = path.join(CUSTOM_DIR, f);
    const content = readFileSync(filePath, 'utf8');
    const nameMatch = content.match(/name:\s*'([^']+)'/);
    const descMatch = content.match(/description:\s*(?:'([^']*)'|"([^"]*)")/);
    return {
      file: f,
      name: nameMatch?.[1] ?? f.replace('.ts', ''),
      description: (descMatch?.[1] ?? descMatch?.[2] ?? 'No description').slice(0, 100),
    };
  });

  const lines = tools.map(t => `  ${t.name} — ${t.description} [${t.file}]`);
  return {
    success: true,
    output: `${tools.length} custom tool(s):\n${lines.join('\n')}`,
    data: tools,
  };
}

function testTool(toolName: string | undefined, testParams: Record<string, unknown> | undefined): ToolResult {
  if (!toolName?.trim()) {
    return { success: false, output: 'toolName is required for test-tool.' };
  }

  const fileName = toFileName(toolName);
  const filePath = path.join(CUSTOM_DIR, fileName);

  if (!existsSync(filePath)) {
    return { success: false, output: `Custom tool file not found: ${filePath}` };
  }

  const content = readFileSync(filePath, 'utf8');

  // Extract metadata from the generated code
  const nameMatch = content.match(/name:\s*'([^']+)'/);
  const descMatch = content.match(/description:\s*(?:'([^']*)'|"([^"]*)")/);
  const paramsMatch = content.match(/parameters:\s*\{([\s\S]*?)\n\s*\},/);
  const hasConfirm = content.includes('requiresConfirmation: true');

  const report = [
    `Tool: ${nameMatch?.[1] ?? 'unknown'}`,
    `Description: ${(descMatch?.[1] ?? descMatch?.[2] ?? 'unknown').slice(0, 200)}`,
    `Requires confirmation: ${hasConfirm ? 'yes' : 'no'}`,
    `File: ${filePath}`,
    `Size: ${content.length} chars`,
    '',
    'Parameter schema (extracted):',
    paramsMatch ? paramsMatch[0].slice(0, 500) : '(could not extract)',
    '',
    `Test params provided: ${testParams ? JSON.stringify(testParams) : 'none'}`,
    '',
    'Syntax check: ' + (content.includes('export const') && content.includes('ToolDefinition') ? 'PASS (exports ToolDefinition)' : 'WARN (may not export correctly)'),
    'Import check: ' + (content.includes("from '../../types.js'") ? 'PASS' : 'WARN (missing types import)'),
    'Error handling: ' + (content.includes('catch (err)') ? 'PASS' : 'WARN (no error handling)'),
  ];

  return {
    success: true,
    output: `Dry-run report for "${toolName}":\n${report.join('\n')}`,
    data: {
      toolName,
      filePath,
      fileSize: content.length,
      syntaxOk: content.includes('export const') && content.includes('ToolDefinition'),
      hasErrorHandling: content.includes('catch (err)'),
      hasConfirmation: hasConfirm,
    },
  };
}

// ---------------------------------------------------------------------------
// Main tool definition
// ---------------------------------------------------------------------------

export const toolCreatorTool: ToolDefinition = {
  name: 'meta.tool-creator',
  description:
    'Template-based tool creator — instantly generate new tools from pre-built templates without LLM calls. ' +
    'Creates file, API, shell, database, or composite tools with safety guards. ' +
    'Faster and cheaper than meta.skill-creator for common tool patterns.',
  category: 'meta',
  timeout: 30_000,
  parameters: {
    action: {
      type: 'string',
      required: true,
      description: 'Action to perform.',
      enum: ['create-file-tool', 'create-api-tool', 'create-shell-tool', 'create-db-tool', 'create-composite-tool', 'list-custom', 'test-tool'],
    },
    toolName: {
      type: 'string',
      description: 'Dot-namespaced tool name (e.g. "custom.my-tool"). Required for create-* and test-tool actions.',
    },
    description: {
      type: 'string',
      description: 'Human-readable description of what the tool does.',
    },
    templateParams: {
      type: 'object',
      description:
        'Template-specific parameters. ' +
        'file-tool: { targetPath, operations: ["read","write","append","delete"] }. ' +
        'api-tool: { baseUrl, method, headers, bodyTemplate }. ' +
        'shell-tool: { command, allowedArgs, timeout }. ' +
        'db-tool: { dbPath, queries: [{ name, sql }] }. ' +
        'composite-tool: { steps: [{ tool, params }] }.',
      properties: {},
    },
    testParams: {
      type: 'object',
      description: 'Parameters for test-tool dry-run.',
      properties: {},
    },
  },

  async execute(params: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
    const action = params['action'] as string;
    const toolName = params['toolName'] as string | undefined;
    const description = (params['description'] as string | undefined) ?? '';
    const templateParams = (params['templateParams'] as Record<string, unknown> | undefined) ?? {};
    const testParams = params['testParams'] as Record<string, unknown> | undefined;

    logger.info({ session: ctx.sessionId, action, toolName }, 'meta.tool-creator invoked');

    try {
      switch (action) {
        case 'create-file-tool': {
          const nameErr = validateToolName(toolName);
          if (nameErr) return nameErr;
          return createFileTool(toolName!, description, templateParams);
        }

        case 'create-api-tool': {
          const nameErr = validateToolName(toolName);
          if (nameErr) return nameErr;
          return createApiTool(toolName!, description, templateParams);
        }

        case 'create-shell-tool': {
          const nameErr = validateToolName(toolName);
          if (nameErr) return nameErr;
          return createShellTool(toolName!, description, templateParams);
        }

        case 'create-db-tool': {
          const nameErr = validateToolName(toolName);
          if (nameErr) return nameErr;
          return createDbTool(toolName!, description, templateParams);
        }

        case 'create-composite-tool': {
          const nameErr = validateToolName(toolName);
          if (nameErr) return nameErr;
          return createCompositeTool(toolName!, description, templateParams);
        }

        case 'list-custom':
          return listCustomTools();

        case 'test-tool':
          return testTool(toolName, testParams);

        default:
          return { success: false, output: `Unknown action: ${action}` };
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error({ action, err: msg }, 'meta.tool-creator error');
      return { success: false, output: `Tool creator error: ${msg}` };
    }
  },
};
