/**
 * meta.undercover — Strip AI attribution from commits and outputs.
 *
 * When enabled, removes "Co-Authored-By: ...SUDO" and "Generated with/by SUDO"
 * lines from commit messages so the agent operates without visible AI attribution.
 *
 * Persists state to data/undercover.json.
 */

import type { ToolDefinition, ToolContext, ToolResult } from '../../types.js';
import { createLogger } from '../../../shared/logger.js';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { DATA_DIR } from '../../../shared/paths.js';

const logger = createLogger('meta.undercover');
const UNDERCOVER_FILE = path.join(DATA_DIR, 'undercover.json');

// ---------------------------------------------------------------------------
// Attribution patterns to strip
// ---------------------------------------------------------------------------

const STRIP_PATTERNS: RegExp[] = [
  /Co-Authored-By:.*SUDO.*/gi,
  /Generated (with|by) SUDO.*/gi,
];

// ---------------------------------------------------------------------------
// Persistence
// ---------------------------------------------------------------------------

interface UndercoverState {
  enabled: boolean;
  enabledAt?: string;
  disabledAt?: string;
  stripCount: number;
}

function ensureDataDir(): void {
  if (!existsSync(DATA_DIR)) mkdirSync(DATA_DIR, { recursive: true });
}

function loadState(): UndercoverState {
  if (existsSync(UNDERCOVER_FILE)) {
    try {
      return JSON.parse(readFileSync(UNDERCOVER_FILE, 'utf8')) as UndercoverState;
    } catch { /* fall through */ }
  }
  return { enabled: false, stripCount: 0 };
}

function saveState(state: UndercoverState): void {
  ensureDataDir();
  writeFileSync(UNDERCOVER_FILE, JSON.stringify(state, null, 2), 'utf8');
}

// ---------------------------------------------------------------------------
// Action handlers
// ---------------------------------------------------------------------------

async function handleEnable(): Promise<ToolResult> {
  const state = loadState();
  state.enabled = true;
  state.enabledAt = new Date().toISOString();
  saveState(state);
  logger.info('Undercover mode ENABLED — AI attribution will be stripped');
  return {
    success: true,
    output: 'Undercover mode ENABLED. AI attribution lines will be stripped from commit messages.',
    data: { enabled: true, enabledAt: state.enabledAt },
  };
}

async function handleDisable(): Promise<ToolResult> {
  const state = loadState();
  state.enabled = false;
  state.disabledAt = new Date().toISOString();
  saveState(state);
  logger.info('Undercover mode DISABLED — AI attribution will appear normally');
  return {
    success: true,
    output: 'Undercover mode DISABLED. AI attribution will appear normally in commit messages.',
    data: { enabled: false, disabledAt: state.disabledAt },
  };
}

async function handleStatus(): Promise<ToolResult> {
  const state = loadState();
  const lines = [
    `Undercover mode: ${state.enabled ? 'ENABLED' : 'DISABLED'}`,
    `Total strips performed: ${state.stripCount}`,
  ];
  if (state.enabledAt) lines.push(`Last enabled: ${new Date(state.enabledAt).toLocaleString()}`);
  if (state.disabledAt) lines.push(`Last disabled: ${new Date(state.disabledAt).toLocaleString()}`);
  return { success: true, output: lines.join('\n'), data: state };
}

async function handleStripCommit(commitMessage?: string): Promise<ToolResult> {
  if (!commitMessage) {
    return {
      success: false,
      output: 'strip-commit requires a commitMessage parameter.',
    };
  }

  let stripped = commitMessage;
  let matchCount = 0;

  for (const pattern of STRIP_PATTERNS) {
    const before = stripped;
    stripped = stripped.replace(pattern, '');
    if (stripped !== before) matchCount++;
  }

  // Clean up any trailing blank lines left by removals
  stripped = stripped.replace(/\n{3,}/g, '\n\n').trim();

  const state = loadState();
  state.stripCount = (state.stripCount ?? 0) + matchCount;
  saveState(state);

  logger.debug({ matchCount, originalLength: commitMessage.length, strippedLength: stripped.length }, 'strip-commit');

  return {
    success: true,
    output: stripped,
    data: {
      original: commitMessage,
      stripped,
      matchCount,
      changed: matchCount > 0,
    },
  };
}

// ---------------------------------------------------------------------------
// Tool definition
// ---------------------------------------------------------------------------

export const undercoverTool: ToolDefinition = {
  name: 'meta.undercover',
  description:
    'Control undercover mode — when enabled, strips AI attribution lines (Co-Authored-By: SUDO, Generated by SUDO) ' +
    'from commit messages and outputs so the agent operates without visible AI branding. ' +
    'Use strip-commit to process a specific commit message string.',
  category: 'meta',
  parameters: {
    action: {
      type: 'string',
      description: 'The undercover action to perform.',
      required: true,
      enum: ['enable', 'disable', 'status', 'strip-commit'],
    },
    commitMessage: {
      type: 'string',
      description: 'The commit message to strip AI attribution from (only used with strip-commit action).',
      required: false,
    },
  },
  timeout: 10_000,

  async execute(params: Record<string, unknown>, _ctx: ToolContext): Promise<ToolResult> {
    const action = params['action'] as string;
    const commitMessage = params['commitMessage'] as string | undefined;
    logger.debug({ action }, 'meta.undercover called');

    switch (action) {
      case 'enable':       return handleEnable();
      case 'disable':      return handleDisable();
      case 'status':       return handleStatus();
      case 'strip-commit': return handleStripCommit(commitMessage);
      default:
        return {
          success: false,
          output: `Unknown action "${action}". Valid: enable, disable, status, strip-commit`,
        };
    }
  },
};
