/**
 * @file proposal-store.ts
 * @description SQLite-backed ProposalStore for AgentConfigProposal persistence.
 *
 * Stores proposals generated by AgentConfigEvolver. Supports list/approve/reject/
 * getById operations. Builder 2 imports this class for learning-routes.ts wiring.
 *
 * DB path: data/proposals.db (isolated from mind.db and wisdom.db).
 *
 * Interface contract (spec G2):
 *   list(filter): { data: AgentConfigProposal[]; total: number }
 *   approve(id): AgentConfigProposal
 *   reject(id, reason?): AgentConfigProposal
 *   getById(id): AgentConfigProposal | null
 */

import Database from 'better-sqlite3';
import { existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { AgentConfigProposal, ProposalStatus } from '../shared/wave10-types.js';
import { createLogger } from '../shared/logger.js';

const log = createLogger('learning:proposal-store');

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

const SCHEMA = `
PRAGMA journal_mode = WAL;
PRAGMA synchronous   = NORMAL;
PRAGMA foreign_keys  = ON;

CREATE TABLE IF NOT EXISTS proposals (
  id            TEXT PRIMARY KEY,
  agent_id      TEXT NOT NULL,
  rationale     TEXT NOT NULL,
  delta_json    TEXT NOT NULL DEFAULT '{}',
  trace_quality REAL NOT NULL DEFAULT 0,
  trace_count   INTEGER NOT NULL DEFAULT 0,
  status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected','applied')),
  reject_reason TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_proposals_status     ON proposals(status);
CREATE INDEX IF NOT EXISTS idx_proposals_agent_id   ON proposals(agent_id);
CREATE INDEX IF NOT EXISTS idx_proposals_created_at ON proposals(created_at DESC);
`;

// ---------------------------------------------------------------------------
// Row type
// ---------------------------------------------------------------------------

interface ProposalRow {
  id: string;
  agent_id: string;
  rationale: string;
  delta_json: string;
  trace_quality: number;
  trace_count: number;
  status: ProposalStatus;
  reject_reason: string | null;
  created_at: string;
  updated_at: string;
}

function rowToProposal(row: ProposalRow): AgentConfigProposal {
  return {
    id: row.id,
    agentId: row.agent_id,
    rationale: row.rationale,
    delta: JSON.parse(row.delta_json) as Record<string, unknown>,
    traceQuality: row.trace_quality,
    traceCount: row.trace_count,
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// ---------------------------------------------------------------------------
// ProposalStore
// ---------------------------------------------------------------------------

export class ProposalStore {
  private readonly db: Database.Database;

  constructor(dbPath = 'data/proposals.db') {
    const dir = dirname(dbPath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    this.db = new Database(dbPath);
    this.db.exec(SCHEMA);
    log.info({ dbPath }, 'ProposalStore initialised');
  }

  // ---------------------------------------------------------------------------
  // Write
  // ---------------------------------------------------------------------------

  /**
   * Persist a new proposal. Returns the stored proposal (with DB timestamps).
   */
  save(proposal: AgentConfigProposal): AgentConfigProposal {
    this.db.prepare(`
      INSERT INTO proposals (id, agent_id, rationale, delta_json, trace_quality, trace_count, status, created_at, updated_at)
      VALUES (:id, :agent_id, :rationale, :delta_json, :trace_quality, :trace_count, :status, :created_at, :updated_at)
    `).run({
      id: proposal.id,
      agent_id: proposal.agentId,
      rationale: proposal.rationale,
      delta_json: JSON.stringify(proposal.delta),
      trace_quality: proposal.traceQuality,
      trace_count: proposal.traceCount,
      status: proposal.status,
      created_at: proposal.createdAt,
      updated_at: proposal.updatedAt,
    });
    log.info({ id: proposal.id, agentId: proposal.agentId }, 'proposal saved');
    return proposal;
  }

  // ---------------------------------------------------------------------------
  // Read
  // ---------------------------------------------------------------------------

  /**
   * List proposals with optional status filter, pagination.
   */
  list(filter: {
    status?: ProposalStatus;
    limit: number;
    offset: number;
  }): { data: AgentConfigProposal[]; total: number } {
    const { status, limit, offset } = filter;

    if (status) {
      const total = (this.db.prepare(
        `SELECT COUNT(*) AS n FROM proposals WHERE status = ?`,
      ).get(status) as { n: number }).n;
      const rows = this.db.prepare(
        `SELECT * FROM proposals WHERE status = ? ORDER BY created_at DESC LIMIT ? OFFSET ?`,
      ).all(status, limit, offset) as ProposalRow[];
      return { data: rows.map(rowToProposal), total };
    }

    const total = (this.db.prepare(
      `SELECT COUNT(*) AS n FROM proposals`,
    ).get() as { n: number }).n;
    const rows = this.db.prepare(
      `SELECT * FROM proposals ORDER BY created_at DESC LIMIT ? OFFSET ?`,
    ).all(limit, offset) as ProposalRow[];
    return { data: rows.map(rowToProposal), total };
  }

  /**
   * Get a single proposal by ID. Returns null if not found.
   */
  getById(id: string): AgentConfigProposal | null {
    const row = this.db.prepare(
      `SELECT * FROM proposals WHERE id = ?`,
    ).get(id) as ProposalRow | undefined;
    return row ? rowToProposal(row) : null;
  }

  /**
   * Mark a proposal as approved. Throws if not found or already applied.
   */
  approve(id: string): AgentConfigProposal {
    const existing = this.getById(id);
    if (!existing) throw new Error(`Proposal not found: ${id}`);
    if (existing.status === 'applied') throw new Error(`Proposal already applied: ${id}`);
    const now = new Date().toISOString();
    this.db.prepare(
      `UPDATE proposals SET status = 'approved', updated_at = ? WHERE id = ?`,
    ).run(now, id);
    return { ...existing, status: 'approved', updatedAt: now };
  }

  /**
   * Mark a proposal as rejected with an optional reason.
   */
  reject(id: string, reason?: string): AgentConfigProposal {
    const existing = this.getById(id);
    if (!existing) throw new Error(`Proposal not found: ${id}`);
    const now = new Date().toISOString();
    this.db.prepare(
      `UPDATE proposals SET status = 'rejected', reject_reason = ?, updated_at = ? WHERE id = ?`,
    ).run(reason ?? null, now, id);
    return { ...existing, status: 'rejected', updatedAt: now };
  }

  /**
   * Mark a proposal as applied (after human approval + actual application).
   */
  markApplied(id: string): AgentConfigProposal {
    const existing = this.getById(id);
    if (!existing) throw new Error(`Proposal not found: ${id}`);
    if (existing.status !== 'approved') {
      throw new Error(`Proposal must be approved before applying: ${id}`);
    }
    const now = new Date().toISOString();
    this.db.prepare(
      `UPDATE proposals SET status = 'applied', updated_at = ? WHERE id = ?`,
    ).run(now, id);
    return { ...existing, status: 'applied', updatedAt: now };
  }

  // ---------------------------------------------------------------------------
  // Lifecycle
  // ---------------------------------------------------------------------------

  close(): void {
    this.db.close();
  }
}
