/**
 * super.build-scraper — Generate a standalone Playwright web scraper.
 *
 * Produces a ready-to-run TypeScript/Node scraper that navigates to a URL
 * and extracts the specified CSS selectors into a structured JSON output.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { createLogger } from '../shared/logger.js';
import type { ToolDefinition, ToolContext, ToolResult, ToolArtifact } from '../tools/types.js';

const logger = createLogger('super.build-scraper');

// ---------------------------------------------------------------------------
// Code generator
// ---------------------------------------------------------------------------

function buildScraperScript(url: string, extract: Record<string, string>): string {
  const extractEntries = Object.entries(extract)
    .map(([name, selector]) => `  ${JSON.stringify(name)}: await page.$$eval(${JSON.stringify(selector)}, els => els.map(e => e.textContent?.trim() ?? '')),`)
    .join('\n');

  return `/**
 * Web Scraper — Generated by super.build-scraper
 * Target: ${url}
 * Run: npx ts-node scraper.ts   OR   node --loader ts-node/esm scraper.ts
 */

import { chromium } from 'playwright';

interface ScrapedData {
${Object.keys(extract).map((k) => `  ${JSON.stringify(k)}: string[];`).join('\n')}
}

async function scrape(): Promise<ScrapedData> {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    userAgent: 'Mozilla/5.0 (compatible; SudoBot/1.0)',
  });
  const page = await context.newPage();

  try {
    await page.goto(${JSON.stringify(url)}, { waitUntil: 'networkidle', timeout: 30_000 });

    const data: ScrapedData = {
${extractEntries}
    };

    await browser.close();
    return data;
  } catch (err) {
    await browser.close();
    throw err;
  }
}

scrape()
  .then((data) => {
    console.log(JSON.stringify(data, null, 2));
    process.exit(0);
  })
  .catch((err: Error) => {
    console.error('[scraper] Error:', err.message);
    process.exit(1);
  });
`;
}

function buildPackageJson(): string {
  return JSON.stringify(
    {
      name: 'generated-scraper',
      version: '1.0.0',
      type: 'module',
      scripts: { scrape: 'npx ts-node scraper.ts' },
      dependencies: { playwright: '^1.40.0' },
      devDependencies: { typescript: '^5.0.0', 'ts-node': '^10.9.0', '@types/node': '^20.0.0' },
    },
    null,
    2,
  );
}

// ---------------------------------------------------------------------------
// Tool definition
// ---------------------------------------------------------------------------

export const scraperBuilderTool: ToolDefinition = {
  name: 'super.build-scraper',
  description: 'Generate a standalone Playwright web scraper that navigates to a URL and extracts data using CSS selectors.',
  category: 'superpowers',
  timeout: 30_000,
  parameters: {
    url: { type: 'string', description: 'Target URL to scrape.', required: true },
    extract: {
      type: 'object',
      description: 'Map of name → CSS selector for each piece of data to extract.',
      required: true,
      properties: {},
    },
    outputPath: { type: 'string', description: 'Absolute path where scraper.ts will be written.', required: true },
  },

  async execute(params: Record<string, unknown>, ctx: ToolContext): Promise<ToolResult> {
    const url = params['url'] as string | undefined;
    const extract = params['extract'] as Record<string, string> | undefined;
    const outputPath = params['outputPath'] as string | undefined;

    if (!url || typeof url !== 'string') return { success: false, output: 'url is required.' };
    if (!extract || typeof extract !== 'object' || Object.keys(extract).length === 0) {
      return { success: false, output: 'extract must be a non-empty object of name → selector pairs.' };
    }
    if (!outputPath) return { success: false, output: 'outputPath is required.' };

    logger.info({ session: ctx.sessionId, url, extractKeys: Object.keys(extract), outputPath }, 'Building scraper');

    try {
      await mkdir(dirname(outputPath), { recursive: true });

      const scraperContent = buildScraperScript(url, extract);
      const packageContent = buildPackageJson();

      const scraperFile = outputPath.endsWith('.ts') ? outputPath : join(outputPath, 'scraper.ts');
      const dir = outputPath.endsWith('.ts') ? dirname(outputPath) : outputPath;
      const packageFile = join(dir, 'package.json');

      await mkdir(dir, { recursive: true });
      await writeFile(scraperFile, scraperContent, 'utf8');
      await writeFile(packageFile, packageContent, 'utf8');

      logger.info({ scraperFile }, 'Scraper generated');

      const artifacts: ToolArtifact[] = [
        { path: scraperFile, action: 'created' },
        { path: packageFile, action: 'created' },
      ];

      return {
        success: true,
        output: `Scraper generated at ${scraperFile}\nSelectors: ${Object.keys(extract).join(', ')}\nRun: cd ${dir} && npm install && npx playwright install chromium && npm run scrape`,
        data: { scraperFile, packageFile, url, selectors: extract },
        artifacts,
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error({ outputPath, err: msg }, 'Scraper generation failed');
      return { success: false, output: `Failed to generate scraper: ${msg}` };
    }
  },
};
