/**
 * @file types.ts
 * @description Core type definitions for the SUDO-AI Knowledge Engine.
 *
 * These interfaces are shared across the Obsidian vault adapter,
 * knowledge graph, research agent, fact extractor, note taker, and
 * Zettelkasten modules.
 */

// ---------------------------------------------------------------------------
// Knowledge Graph
// ---------------------------------------------------------------------------

/**
 * A node in the knowledge graph — a discrete piece of knowledge
 * with a type, title, freeform content, and optional tags.
 */
export interface KnowledgeNode {
  /** Auto-assigned integer primary key. */
  id: number;
  /**
   * Semantic type of the node.
   * - concept: An idea or topic
   * - fact: A verifiable claim with a source
   * - note: A personal observation or synthesis
   * - entity: A named real-world thing (person, place, org)
   * - source: A document, URL, or reference
   */
  type: 'concept' | 'fact' | 'note' | 'entity' | 'source';
  /** Human-readable title or headline. */
  title: string;
  /** Full content / body text. */
  content: string;
  /** Searchable tags. */
  tags: string[];
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  /** ISO 8601 last-modified timestamp. */
  updatedAt: string;
  /** ISO 8601 timestamp when this node becomes valid (null = always valid from creation). */
  validAt: string | null;
  /** ISO 8601 timestamp when this node expires / is superseded (null = never expires). */
  expiredAt: string | null;
}

/**
 * A directed, weighted edge between two knowledge nodes.
 */
export interface KnowledgeEdge {
  /** Auto-assigned integer primary key. */
  id: number;
  /** Source node ID. */
  fromId: number;
  /** Target node ID. */
  toId: number;
  /**
   * Semantic relation label.
   * E.g. "supports", "contradicts", "relates-to", "derived-from", "cites"
   */
  relation: string;
  /** Importance weight in [0, 1]. Defaults to 1.0. */
  weight: number;
  /** Arbitrary key-value metadata for this edge. */
  properties: Record<string, unknown>;
  /** ISO 8601 timestamp when this edge becomes valid (null = always valid from creation). */
  validAt: string | null;
}

// ---------------------------------------------------------------------------
// Research
// ---------------------------------------------------------------------------

/**
 * Aggregated result from ResearchAgent.research().
 */
export interface ResearchResult {
  /** Topic that was researched. */
  topic: string;
  /** Summary synthesised from all sources. */
  summary: string;
  /** Facts extracted across all sources. */
  facts: Fact[];
  /** Related knowledge graph nodes found. */
  graphNodes: KnowledgeNode[];
  /** Vault notes found (paths). */
  vaultNotes: string[];
  /** Web snippets or search results (text). */
  webSnippets: string[];
  /** ISO 8601 timestamp of when research ran. */
  researchedAt: string;
}

// ---------------------------------------------------------------------------
// Facts
// ---------------------------------------------------------------------------

/**
 * A discrete, extractable fact from a body of text.
 */
export interface Fact {
  /** Category of the fact. */
  type: 'number' | 'entity' | 'claim' | 'date';
  /** The raw text of the extracted fact. */
  text: string;
  /** Surrounding context sentence (for provenance). */
  context: string;
  /** Confidence score in [0, 1]. */
  confidence: number;
}

// ---------------------------------------------------------------------------
// Notes
// ---------------------------------------------------------------------------

/**
 * A structured note generated by the note taker.
 */
export interface Note {
  /**
   * Format of the note:
   * - zettelkasten: One atomic idea per card with unique ID
   * - outline: Hierarchical bullet structure
   * - cornell: Summary / notes / questions sections
   */
  format: 'zettelkasten' | 'outline' | 'cornell';
  /** Generated title. */
  title: string;
  /** Full note content in Markdown. */
  content: string;
  /** Tags derived from the source text. */
  tags: string[];
  /** For zettelkasten notes — unique ID (e.g. YYYYMMDDHHmm). */
  zettelId?: string;
}

// ---------------------------------------------------------------------------
// Obsidian
// ---------------------------------------------------------------------------

/**
 * A parsed Obsidian Markdown note with frontmatter.
 */
export interface ObsidianNote {
  /** Absolute path to the .md file. */
  path: string;
  /** Raw filename without extension. */
  name: string;
  /** Parsed YAML frontmatter as a key-value map. */
  frontmatter: Record<string, unknown>;
  /** Body text below the frontmatter block. */
  body: string;
  /** Wikilinks found in the note body ([[target]]). */
  wikilinks: string[];
  /** ISO 8601 modified time of the file. */
  modifiedAt: string;
}
