/**
 * @file workflows/types.ts
 * @description Shared type definitions for the Lobster workflow engine.
 */

export interface WorkflowStep {
  id: string;
  /** Shell command or tool name. */
  command: string;
  /** Execution mode — defaults to 'shell'. */
  type?: 'shell' | 'tool';
  /** Static stdin value, or `{{prev}}` / `{{steps.<id>.<field>}}` template. */
  stdin?: string;
  /** If true, the engine pauses here and emits a resumeToken. */
  approval?: boolean;
  /**
   * Simple guard expression evaluated against completed step results.
   * Supported operators: `===`, `!==`, `&&`, `||`.
   * Supported atoms: `steps.<id>.<field>`, number literals, boolean literals,
   * quoted strings.
   * Example: `"steps.check-disk.exitCode === 0"`
   */
  condition?: string;
  /** Execution timeout in milliseconds — process is killed on expiry. */
  timeout?: number;
  /**
   * Fan-out marker (slice 2). Consecutive steps that share the same
   * `parallel_group` label run concurrently — bounded by a per-engine semaphore
   * (default 4, env `SUDO_WORKFLOWS_MAX_PARALLEL`). The group's runtime ends
   * when every member settles; only then does the engine advance past the
   * group. Inside a group `{{prev}}` is forbidden (no defined ordering) — use
   * explicit `{{steps.<id>.<field>}}` templating against a step outside the
   * group instead.
   */
  parallel_group?: string;
  /**
   * Named synchronization barrier (slice 3). Consecutive steps sharing a
   * `phase` value form a phase block: ALL members fan out concurrently into
   * the same per-engine worker pool used by `parallel_group` (bounded by
   * `SUDO_WORKFLOWS_MAX_PARALLEL`, default 4). A hard barrier sits at the end
   * of every phase — the next phase (or any sequential step after) cannot
   * start until every phase member settles. Failure of any member halts the
   * workflow after the rest of the phase settles, matching `parallel_group`
   * semantics.
   *
   * Difference vs `parallel_group`: phase blocks are named stages that often
   * span heterogeneous work (fetch + transform + validate together under one
   * stage label), where `parallel_group` is a peer fan-out. The two are
   * mutually exclusive on the same step — pick one fan-out scope per step.
   *
   * `{{prev}}` and `approval: true` are forbidden inside a phase for the same
   * reason as inside a parallel_group: phase members have no defined ordering,
   * so "the previous step" is ambiguous and an approval gate has no resume
   * semantics across a fan-out.
   */
  phase?: string;
}

export interface Workflow {
  name: string;
  description?: string;
  steps: WorkflowStep[];
}

export interface StepResult {
  id: string;
  status: 'success' | 'failure' | 'skipped' | 'awaiting_approval';
  stdout?: string;
  stderr?: string;
  exitCode?: number;
  durationMs: number;
}

export interface WorkflowRunState {
  workflowName: string;
  startedAt: string;
  completedSteps: StepResult[];
  /** Set when the engine pauses on an approval gate. */
  pendingStepIndex?: number;
  /**
   * Step id the engine paused on. Carried alongside pendingStepIndex so a
   * resumer can identify the approved step by id (stable) rather than by
   * index (which shifts if the workflow file is edited between pause and resume).
   */
  pendingStepId?: string;
  /** UUID for resuming a paused workflow. */
  resumeToken?: string;
  /**
   * Stable per-run id (slice 2). Persisted into the on-disk journal filename
   * and re-used across pause/resume so the same journal file is rewritten,
   * not orphaned. Generated by the engine at first run.
   */
  runId?: string;
}

/** Outcome returned by a {@link ToolStepExecutor} for a `type: 'tool'` step. */
export interface ToolStepResult {
  /** Whether the dispatched tool reported success. */
  success: boolean;
  /** Model-facing text output; becomes the step's stdout so `{{prev}}` threading works. */
  stdout?: string;
  /** Error detail on failure; becomes the step's stderr. */
  stderr?: string;
}

/**
 * Executes a `type: 'tool'` step by dispatching `step.command` (a host tool
 * name) to the tool registry. Supplied by the caller (meta.run-workflow) so the
 * engine stays decoupled from the ToolRegistry. When absent, tool steps fail
 * HONESTLY rather than silently succeeding.
 *
 * @param step          - The tool step (`step.command` is the tool name).
 * @param resolvedStdin - The step's stdin after `{{prev}}` resolution, or undefined.
 */
export type ToolStepExecutor = (
  step: WorkflowStep,
  resolvedStdin: string | undefined,
) => Promise<ToolStepResult>;

export interface RunOptions {
  /** Supply to resume execution after an approval gate was unblocked. */
  resumeState?: WorkflowRunState;
  /**
   * Called when a step has `approval: true`.
   * Return `true` to continue immediately; `false` to pause and save state.
   */
  approvalCallback?: (step: WorkflowStep, runState: WorkflowRunState) => Promise<boolean>;
  /**
   * Dispatches `type: 'tool'` steps to the host tool registry. When omitted,
   * tool steps record an honest failure instead of executing.
   */
  toolExecutor?: ToolStepExecutor;
  /**
   * Max in-flight steps within one `parallel_group` or `phase` block.
   * Outside a fan-out block, steps still run sequentially. Default 4 when
   * omitted. The caller layer reads `SUDO_WORKFLOWS_MAX_PARALLEL` and passes
   * it down.
   */
  maxParallel?: number;
  /**
   * Pre-assigned run id. When supplied, the engine uses it as the journal
   * filename anchor; otherwise the engine mints one. Mostly useful for tests
   * and for callers that want filename/id continuity established before run.
   */
  runId?: string;
  /**
   * Opt-in on-disk resume journal (slice 2). Path to a JSON file the engine
   * rewrites after every settled step. The file embeds the run id plus a
   * SHA-256 of the workflow YAML source so a resume call refuses to replay
   * against an edited file.
   */
  journalPath?: string;
  /**
   * SHA-256 of the workflow source bytes — supplied by the caller so the
   * engine can record it in the journal without re-reading the file. Required
   * when {@link journalPath} is set.
   */
  sourceSha256?: string;
}

/**
 * On-disk resume journal record. The engine rewrites this file atomically
 * after every settled step (slice 2).
 */
export interface WorkflowJournal {
  /** Random per-run identifier — embedded in the journal filename too. */
  runId: string;
  /** SHA-256 of the workflow YAML source at run start (lowercase hex). */
  sourceSha256: string;
  /** Journal schema version — bump on incompatible shape changes. */
  version: 1;
  /** Current run state — the same object resume_state accepts. */
  state: WorkflowRunState;
}
