/**
 * @file config/flag-lint.ts
 * @description GW-10: boot-time config sanity. Two jobs:
 *   1. GHOST FLAGS — env `SUDO_*` names that no code reads (compared against the
 *      committed manifest generated by scripts/gen-flag-manifest.ts). WARN only.
 *   2. CONTRADICTIONS — known-bad flag combos that REFUSE BOOT unless
 *      SUDO_ALLOW_CONTRADICTORY_CONFIG=1 (posture-registered).
 *   plus non-fatal WARNINGS (auth precedence ambiguity; missing file SecretRef).
 *
 * Pure + injectable (env, manifest, fileExists) so every rule is unit-testable.
 * The contradiction table is exported so GW-7's `flags.contradiction` audit
 * check reuses the SAME rules (single source of truth).
 */

import { existsSync } from 'node:fs';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ContradictionHit {
  id: string;
  detail: string;
}

export interface FlagLintResult {
  /** SUDO_* env names present but absent from the manifest (no code reads them). */
  ghosts: string[];
  /** Active known-bad combos. Non-empty → refuse boot unless override set. */
  contradictions: ContradictionHit[];
  /** Non-fatal advisories. */
  warnings: string[];
}

export interface LintDeps {
  /** File-existence probe (injected for tests). */
  fileExists?: (p: string) => boolean;
}

/** A contradiction rule: returns a detail string when the bad combo is active, else false. */
export interface Contradiction {
  id: string;
  test: (env: NodeJS.ProcessEnv, deps: Required<LintDeps>) => string | false;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function truthy(v: string | undefined): boolean {
  return v !== undefined && v !== '' && v !== '0' && v.toLowerCase() !== 'false' && v.toLowerCase() !== 'off';
}

/** True if any untrusted inbound channel is enabled (the sandbox must stay on). Exported so GW-7's security audit shares the same definition. */
export function untrustedInboundActive(env: NodeJS.ProcessEnv): string[] {
  const on: string[] = [];
  if (truthy(env['WEBHOOKS_ENABLED'])) on.push('WEBHOOKS_ENABLED');
  if (truthy(env['EMAIL_IMAP_HOST']) || truthy(env['EMAIL_IMAP_PASS'])) on.push('EMAIL_IMAP');
  if (truthy(env['WHATSAPP_TOKEN'])) on.push('WHATSAPP');
  // GW-6 pairing/open DM policy — env hook so this stays correct once GW-6 lands.
  const dm = (env['SUDO_DM_POLICY'] ?? '').toLowerCase();
  if (dm === 'open' || dm === 'pairing') on.push(`dmPolicy=${dm}`);
  return on;
}

/** Loopback host literals. A bind to anything else is "exposed". */
function isLoopbackHost(h: string | undefined): boolean {
  if (!h) return true; // unset → default loopback bind
  const v = h.trim().toLowerCase();
  return v === '' || v === '127.0.0.1' || v === '::1' || v === 'localhost';
}

/** True when a configured bind exposes beyond loopback. */
function isNonLoopbackBind(env: NodeJS.ProcessEnv): boolean {
  for (const key of ['SUDO_GATEWAY_BIND', 'SUDO_DASHBOARD_BIND', 'WEB_CHAT_BIND', 'BIND_ADDRESS']) {
    const v = env[key];
    if (v !== undefined && !isLoopbackHost(v)) return true;
  }
  return false;
}

/** Parse a `<NAME>_REF` value; return its referenced file path when source=file. */
function refFilePath(raw: string): string | null {
  try {
    const parsed = JSON.parse(raw) as { source?: string; id?: string };
    if (parsed && parsed.source === 'file' && typeof parsed.id === 'string') {
      return parsed.id.split('#')[0] ?? null;
    }
  } catch {
    /* not JSON → not a file SecretRef we can check */
  }
  return null;
}

// ---------------------------------------------------------------------------
// Contradiction table (shared with GW-7 flags.contradiction)
// ---------------------------------------------------------------------------

export const CONTRADICTIONS: readonly Contradiction[] = [
  {
    id: 'unified-auth-off-with-token',
    test: (env) =>
      env['SUDO_GATEWAY_UNIFIED_AUTH'] === '0' && truthy(env['GATEWAY_TOKEN'])
        ? 'SUDO_GATEWAY_UNIFIED_AUTH=0 (legacy auth) while GATEWAY_TOKEN is set — the token is only honored on loopback-direct requests under the kill-switch'
        : false,
  },
  {
    id: 'sandbox-disabled-with-untrusted-inbound',
    test: (env) => {
      if (env['SUDO_SANDBOX_DISABLE'] !== '1') return false;
      const inbound = untrustedInboundActive(env);
      return inbound.length > 0
        ? `SUDO_SANDBOX_DISABLE=1 while untrusted inbound channels are active (${inbound.join(', ')}) — untrusted code would run unsandboxed`
        : false;
    },
  },
  {
    id: 'web-chat-no-token-exposed',
    test: (env) =>
      env['WEB_CHAT_ENABLED'] === 'true' && !truthy(env['WEB_CHAT_TOKEN']) && isNonLoopbackBind(env)
        ? 'WEB_CHAT_ENABLED=true without WEB_CHAT_TOKEN on a non-loopback bind — open chat exposed to the network'
        : false,
  },
] as const;

// ---------------------------------------------------------------------------
// Lint
// ---------------------------------------------------------------------------

/** GW-10: is the contradiction override active (posture-registered)? */
export function isContradictionOverride(env: NodeJS.ProcessEnv = process.env): boolean {
  return env['SUDO_ALLOW_CONTRADICTORY_CONFIG'] === '1';
}

/**
 * GW-10 (MEDIUM-2): file SecretRefs pointing at a nonexistent path used to be a
 * boot-REFUSAL contradiction. Downgraded to a loud WARNING: a missing SecretRef
 * file already fails at RESOLUTION time where the cred is actually used, and prod
 * is mid-migration to file `_REF` creds — bricking boot on a not-yet-provisioned
 * path is too aggressive. Prefix the id for stable assertions/greps.
 */
function secretsRefWarnings(env: NodeJS.ProcessEnv, deps: Required<LintDeps>): string[] {
  if (env['SUDO_SECRETS_REF'] === '0') return []; // SecretRef disabled
  const out: string[] = [];
  for (const [k, v] of Object.entries(env)) {
    if (!k.endsWith('_REF') || typeof v !== 'string') continue;
    const fp = refFilePath(v);
    if (fp && !deps.fileExists(fp)) {
      out.push(
        `secrets-ref-missing-file: ${k} is a file SecretRef pointing to a nonexistent path (${fp}) — ` +
          `resolution will fail where the cred is used; NOT fatal at boot (prod mid-migration to file _REF creds)`,
      );
    }
  }
  return out;
}

const SUDO_FLAG_RE = /^SUDO_[A-Z0-9_]+$/;

/**
 * Run the full flag lint. `manifest` is the committed list of SUDO_* names the
 * code actually reads. Pure — no process exit, no throw; the caller decides
 * whether contradictions are fatal (they are, unless the override is set).
 */
export function lintFlags(
  env: NodeJS.ProcessEnv,
  manifest: readonly string[],
  deps: LintDeps = {},
): FlagLintResult {
  const resolved: Required<LintDeps> = { fileExists: deps.fileExists ?? existsSync };
  const known = new Set(manifest);

  const ghosts = Object.keys(env)
    .filter((k) => SUDO_FLAG_RE.test(k) && !known.has(k))
    .sort();

  const contradictions: ContradictionHit[] = [];
  for (const c of CONTRADICTIONS) {
    const detail = c.test(env, resolved);
    if (detail) contradictions.push({ id: c.id, detail });
  }

  const warnings: string[] = [];
  warnings.push(...secretsRefWarnings(env, resolved));
  const tok = env['GATEWAY_TOKEN'];
  const sec = env['GATEWAY_SECRET'];
  if (truthy(tok) && truthy(sec) && tok !== sec) {
    warnings.push(
      'GATEWAY_TOKEN and GATEWAY_SECRET are both set to different values — both map to operator.admin today; precedence is GATEWAY_TOKEN first (see docs/gateway-unified.md)',
    );
  }

  return { ghosts, contradictions, warnings };
}
