/**
 * @file error-reporter-helpers.ts
 * @description Helper functions for ErrorReporter (GitHub issue creation, env resolution).
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import { readFileSync } from 'fs';
import { ErrorSeverity, ErrorContext } from './error-reporter.js';
import { GitHubIssuesConnector } from '../channels/github-issues.js';

const execAsync = promisify(exec);

/**
 * Get the current git commit SHA.
 */
export async function getCommitSha(): Promise<string | null> {
  try {
    const { stdout } = await execAsync('git rev-parse HEAD');
    return stdout.trim();
  } catch {
    return null;
  }
}

/**
 * Get the SUDO version from package.json.
 */
export async function getVersion(): Promise<string | null> {
  try {
    const pkg = JSON.parse(readFileSync('/root/sudo-ai-v4/package.json', 'utf-8'));
    return pkg.version ?? null;
  } catch {
    return null;
  }
}

/**
 * Build the issue body for a GitHub issue.
 */
export function buildIssueBody(
  error: Error,
  severity: ErrorSeverity,
  context: ErrorContext,
  signature: string,
  timestamp: string,
  nodeVersion: string,
  commitSha: string | null,
  version: string | null,
): string {
  return [
    '## Error Details',
    '',
    `**Severity:** ${severity}`,
    `**Timestamp:** ${timestamp}`,
    `**Signature:** \`${signature}\``,
    '',
    '## Stack Trace',
    '```',
    error.stack ?? error.message,
    '```',
    '',
    '## Environment',
    '',
    `**Node Version:** ${nodeVersion}`,
    `**Commit SHA:** ${commitSha || 'unknown'}`,
    `**SUDO Version:** ${version || 'unknown'}`,
    `**Tool/Check:** ${context.toolName ?? context.healthCheck ?? 'unknown'}`,
    '',
    '## Context',
    '```json',
    JSON.stringify(context, null, 2),
    '```',
    '',
    '---',
    '*Auto-generated by ErrorReporter*',
  ].join('\n');
}

/**
 * Build the comment body for an occurrence.
 */
export function buildOccurrenceComment(
  error: Error,
  severity: ErrorSeverity,
  context: ErrorContext,
  timestamp: string,
): string {
  return [
    '## New Occurrence',
    '',
    `**Timestamp:** ${timestamp}`,
    `**Severity:** ${severity}`,
    '',
    '```',
    error.message.slice(0, 500),
    '```',
    '',
    `**Context:** ${JSON.stringify(context, null, 2)}`,
  ].join('\n');
}

/**
 * Build the issue title.
 */
export function buildIssueTitle(error: Error, severity: ErrorSeverity): string {
  return `[auto-bug] ${severity}: ${error.message.slice(0, 80).replace(/\n/g, ' ')}`;
}
