/**
 * @file cli/commands/quickstart.ts
 * @description sudo-ai quickstart — interactive 5-step setup wizard (legacy readline).
 *
 * Wave 10 — Builder 3 (Config + Ops + UX)
 * Wave2 polish: compat preserved; recommends full Ink TUI `sudo-ai setup` for 100x (cross/P1, xai-auth, profiles, kills, SOUL, service, learner/KAIROS).
 *
 * Wizard steps:
 *   1. Agent name → meta.name
 *   2. Model choice (lists primary options)
 *   3. Enable Telegram? (y/n)
 *   4. Pick preset: coding/research/chat
 *   5. Run doctor now? (y/n)
 *
 * Writes initial config/sudo-ai.json5.
 * Never overwrites existing config without --force.
 * Always exits 0.
 *
 * Uses Node.js readline only — no external deps.
 * For full real-time Ink TUI wizard (like chat TUI) + 100x coverage + ongoing + first-run: use `sudo-ai setup`.
 */

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const AVAILABLE_MODELS = [
  { id: 'ollama/deepseek-v4-pro:cloud', label: 'ollama/deepseek-v4-pro:cloud (recommended — cloud)' },
  { id: 'xai/grok-4-0709',            label: 'xai/grok-4-0709 (premium, max capability)' },
  { id: 'xai/grok-4-1-fast-non-reasoning', label: 'xai/grok-4-1-fast (fast + cheap)' },
  { id: 'anthropic/claude-sonnet-4-5', label: 'anthropic/claude-sonnet-4-5 (balanced)' },
  { id: 'openai/gpt-4o',               label: 'openai/gpt-4o (OpenAI flagship)' },
  { id: 'google/gemini-2.0-flash',     label: 'google/gemini-2.0-flash (efficient)' },
];

const PRESET_DESCRIPTIONS: Record<string, string> = {
  coding:   'Developer assistant — code review, debugging, architecture',
  research: 'Research analyst — literature review, synthesis, long context',
  chat:     'Conversational assistant — fast responses, messaging channels',
};

// ---------------------------------------------------------------------------
// Readline helpers
// ---------------------------------------------------------------------------

function createInterface(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

async function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

async function promptWithDefault(
  rl: readline.Interface,
  question: string,
  defaultValue: string,
): Promise<string> {
  const answer = await prompt(rl, `${question} [${defaultValue}]: `);
  return answer.length > 0 ? answer : defaultValue;
}

async function promptYesNo(
  rl: readline.Interface,
  question: string,
  defaultYes: boolean = true,
): Promise<boolean> {
  const hint = defaultYes ? 'Y/n' : 'y/N';
  const answer = await prompt(rl, `${question} [${hint}]: `);
  if (answer.length === 0) return defaultYes;
  return answer.toLowerCase().startsWith('y');
}

// ---------------------------------------------------------------------------
// Config template builder
// ---------------------------------------------------------------------------

interface WizardAnswers {
  agentName: string;
  defaultModel: string;
  enableTelegram: boolean;
  preset: string;
}

function buildConfigJson5(answers: WizardAnswers): string {
  const telegramSection = answers.enableTelegram
    ? `
    telegram: {
      enabled: true,
      tokenEnvKey: 'TELEGRAM_BOT_TOKEN',
      allowedUsers: [],
    },`
    : `
    telegram: {
      enabled: false,
      tokenEnvKey: 'TELEGRAM_BOT_TOKEN',
      allowedUsers: [],
    },`;

  return `// SUDO-AI Configuration — generated by quickstart wizard
// Edit this file or run 'sudo-ai init --preset <name>' to apply a preset.
// Docs: https://github.com/sudo-ai/sudo-ai
{
  meta: {
    name: ${JSON.stringify(answers.agentName)},
    timezone: 'UTC',
  },
  agents: {
    maxIterations: 150,
    systemPrompt: ${JSON.stringify(`You are ${answers.agentName}. Be helpful, concise, and accurate.`)},
  },
  models: {
    primary: [
      {
        id: '${answers.defaultModel}',
        contextWindow: 131072,
        maxOutputTokens: 8192,
        temperature: 0.7,
      },
    ],
    fallback: {
      id: 'xai/grok-4-1-fast-non-reasoning',
      contextWindow: 131072,
      maxOutputTokens: 4096,
      temperature: 0.7,
    },
    embedding: {
      id: 'openai/text-embedding-3-small',
      dims: 1536,
    },
  },
  auth: {
    xai:       { envKey: 'XAI_API_KEY' },
    openai:    { envKey: 'OPENAI_API_KEY' },
    anthropic: { envKey: 'ANTHROPIC_API_KEY' },
    google:    { envKey: 'GOOGLE_API_KEY' },
  },
  channels: {${telegramSection}
    whatsapp: { enabled: false, sessionPath: 'data/whatsapp', allowedJids: [] },
    discord:  { enabled: false, tokenEnvKey: 'DISCORD_BOT_TOKEN', allowedChannelIds: [] },
  },
  tools: {
    disabled: [],
    browser: { headless: true, timeoutMs: 30000 },
  },
  cron: {
    jobs: [],
  },
  gateway: {
    enabled: true,
    port: 18900,
    allowedHosts: ['localhost', '127.0.0.1'],
    secretEnvKey: 'GATEWAY_TOKEN',
  },
}
`;
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export interface QuickstartOptions {
  force?: boolean;
}

/**
 * Run the interactive quickstart wizard.
 *
 * @param projectRoot - Absolute path to the project root.
 * @param opts        - { force?: boolean } — overwrite existing config
 * @returns Always exits 0.
 */
export async function runQuickstart(
  projectRoot: string,
  opts: QuickstartOptions = {},
): Promise<void> {
  const configPath = path.join(projectRoot, 'config', 'sudo-ai.json5');
  const configDir  = path.join(projectRoot, 'config');

  console.log('\n  SUDO-AI Quickstart Wizard');
  console.log('  ='.repeat(25));

  // Check for existing config
  if (fs.existsSync(configPath) && !opts.force) {
    console.log(`\n  Existing config found at: ${configPath}`);
    console.log('  Use --force to overwrite it.\n');
    return;
  }

  const rl = createInterface();

  try {
    // Step 1: Agent name
    console.log('\n  Step 1/5: Agent name');
    const agentName = await promptWithDefault(rl, '  What should your agent be named?', 'SUDO-AI');

    // Step 2: Model choice
    console.log('\n  Step 2/5: Model selection');
    console.log('  Available models:');
    AVAILABLE_MODELS.forEach((m, i) => {
      console.log(`    ${i + 1}. ${m.label}`);
    });
    const modelInput = await promptWithDefault(rl, '  Enter number (1-6)', '1');
    const modelIndex = Math.max(0, Math.min(AVAILABLE_MODELS.length - 1, parseInt(modelInput, 10) - 1));
    const defaultModel = AVAILABLE_MODELS[modelIndex]?.id ?? AVAILABLE_MODELS[0]!.id;
    console.log(`  Selected: ${defaultModel}`);

    // Step 3: Telegram
    console.log('\n  Step 3/5: Telegram channel');
    const enableTelegram = await promptYesNo(rl, '  Enable Telegram integration?', false);
    if (enableTelegram) {
      console.log('  Set TELEGRAM_BOT_TOKEN in config/.env to complete Telegram setup.');
    }

    // Step 4: Preset
    console.log('\n  Step 4/5: Configuration preset');
    console.log('  Available presets:');
    Object.entries(PRESET_DESCRIPTIONS).forEach(([name, desc]) => {
      console.log(`    ${name.padEnd(12)} — ${desc}`);
    });
    const presetInput = await promptWithDefault(rl, '  Enter preset name', 'chat');
    const preset = Object.keys(PRESET_DESCRIPTIONS).includes(presetInput.toLowerCase())
      ? presetInput.toLowerCase()
      : 'chat';
    console.log(`  Selected preset: ${preset}`);

    // Step 5: Run doctor
    console.log('\n  Step 5/5: Health check');
    const runDoctorNow = await promptYesNo(rl, '  Run sudo-ai doctor now?', true);

    // Write config
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }

    const answers: WizardAnswers = { agentName, defaultModel, enableTelegram, preset };
    const configContent = buildConfigJson5(answers);
    fs.writeFileSync(configPath, configContent, 'utf8');

    console.log(`\n  Config written to: ${configPath}`);
    console.log(`  Preset selected: ${preset} (run 'sudo-ai init --preset ${preset}' to apply)`);
    console.log('  Next steps:');
    console.log('    1. Edit config/.env with your API keys (or re-run with full TUI)');
    console.log('    2. For the full setup wizard (providers, profiles, service): run `sudo-ai setup`');
    console.log('    3. Run: sudo-ai doctor');
    console.log('    4. Run: sudo-ai start\n');

    if (runDoctorNow) {
      console.log('  Running health check...\n');
      const { runDoctor } = await import('./doctor.js');
      await runDoctor(projectRoot);
    }
  } finally {
    rl.close();
  }
}
