/**
 * @file cli/commands/setup.ts
 * @description sudo-ai setup — full Ink TUI wizard for first-time + ongoing 100x setup.
 *
 * Wave2 Setup Wizard Polish (general-purpose).
 * - Real-time Ink TUI like chat/ (React + ink, useInput/useApp, TextInput, palette from tui-v4-spec).
 * - Covers exactly: name/model/xai-auth/100x P1 cross enable (tools/sandbox/learner/KAIROS)/profiles/kills/SOUL/service.
 * - Writes: sudo-ai.json5 (enhanced), sudo-ai.toml (extended), config/.env (keys + kills), optional profile skeleton.
 * - Auto first-run support: ensureFirstRunWizard(projectRoot) — call from index for bare `sudo-ai`.
 * - Ongoing: `sudo-ai setup` (or via config --setup once wired).
 * - Non-TTY / --yes: defaults + env for CI/tests (100x enabled by default).
 * - Reuses patterns from chat/components (imports only; NO edits to chat/* / App / core per boundaries).
 * - No new npm deps. Arsenal small + tsc verify. Strict Wave2 boundaries only.
 *
 * Usage:
 *   tsx src/cli/commands/setup.ts
 *   (after index wire: sudo-ai setup)
 */

import React, { useState, useEffect, useCallback } from 'react';
import { render, Box, Text, useApp, useInput } from 'ink';
import TextInput from 'ink-text-input';
import fs from 'node:fs';
import path from 'node:path';
import JSON5 from 'json5';

// Reusable Ink wizard component (setup* area, no Wave3 overlap)
import { SetupSelect, type SetupSelectItem } from './setup/components/SetupSelect.js';

// Reusable chat patterns (imports ONLY; never edit chat/ per explicit boundaries + confirm)
import { Banner } from './chat/components/Banner.js';
import { Rule } from './chat/components/Rule.js';

// ---------------------------------------------------------------------------
// Types & Constants (100x coverage)
// ---------------------------------------------------------------------------

export interface SetupOptions {
  yes?: boolean;   // non-interactive defaults (for tests/CI)
  force?: boolean; // overwrite without prompt
}

interface WizardAnswers {
  agentName: string;
  xaiKey: string;           // written to .env if provided
  defaultModel: string;
  enableCross: boolean;     // 100x P1 IComputerUse + learner on control
  enableProfiles: boolean;
  enableToolLearning: boolean;
  enableSandbox: boolean;   // note: dangerous if false
  adoptSoul: boolean;
  setupService: boolean;    // pm2 vs systemd note
}

const AVAILABLE_MODELS: SetupSelectItem[] = [
  { value: 'xai/grok-4-1-fast-non-reasoning', label: 'xai/grok-4-1-fast (fast + cheap, recommended for 100x)', desc: '' },
  { value: 'xai/grok-4-0709', label: 'xai/grok-4-0709 (premium, max capability)', desc: '' },
  { value: 'ollama/deepseek-v4-pro:cloud', label: 'ollama/deepseek-v4-pro:cloud (cloud, no local GPU needed)', desc: '' },
  { value: 'anthropic/claude-sonnet-4-5', label: 'anthropic/claude-sonnet-4-5 (balanced)', desc: '' },
  { value: 'openai/gpt-4o', label: 'openai/gpt-4o (OpenAI flagship)', desc: '' },
  { value: 'google/gemini-2.0-flash', label: 'google/gemini-2.0-flash (efficient)', desc: '' },
];

const KILL_KEYS = {
  cross: 'SUDO_CROSS_CONTROL_DISABLE',      // P1 IComputerUse (see post-remed Codex notes)
  profiles: 'SUDO_PROFILES_DISABLE',
  toolLearning: 'SUDO_TOOL_LEARNING_DISABLE', // ToolOutcomeLearner 100x
  sandbox: 'SUDO_SANDBOX_DISABLE',
} as const;

// ---------------------------------------------------------------------------
// Config builders (enhanced from quickstart/init for 100x; small surgical)
// ---------------------------------------------------------------------------

function buildSetupJson5(answers: WizardAnswers): string {
  const crossComment = answers.enableCross
    ? '\n    // 100x P1: cross-platform IComputerUse enabled (exec/file/GUI/desktop/browser on 3OS + learner on outcomes). Set SUDO_CROSS...=1 to disable.'
    : '\n    // 100x P1 cross DISABLED (set env to 0 to enable full control).';
  const profileComment = answers.enableProfiles
    ? '\n    // 100x: multi-profile isolation enabled (see data/profiles/).'
    : '\n    // 100x profiles disabled via kill.';
  const learnerComment = answers.enableToolLearning
    ? '\n    // 100x: ToolOutcomeLearner + self-improvement active on tools/control.'
    : '';

  return `// SUDO-AI Configuration — generated by 'sudo-ai setup' (Wave2 full Ink TUI wizard)
// Edit or re-run 'sudo-ai setup' for ongoing changes. Docs: https://github.com/sudo-ai/sudo-ai
// 100x: cross/P1, profiles, learner, KAIROS, SOUL (uncensored owner power), kills via .env
{
  meta: {
    name: ${JSON.stringify(answers.agentName)},
    timezone: 'UTC',
  },
  agents: {
    maxIterations: 150,
    systemPrompt: ${JSON.stringify(`You are ${answers.agentName}. Be helpful, concise, accurate. Owner loyalty per SOUL.`)},
  },
  models: {
    primary: [
      {
        id: '${answers.defaultModel}',
        contextWindow: 131072,
        maxOutputTokens: 8192,
        temperature: 0.7,
      },
    ],
    fallback: {
      id: 'xai/grok-4-1-fast-non-reasoning',
      contextWindow: 131072,
      maxOutputTokens: 4096,
      temperature: 0.7,
    },
    embedding: { id: 'openai/text-embedding-3-small', dims: 1536 },
  },
  auth: {
    xai: { envKey: 'XAI_API_KEY' },
    openai: { envKey: 'OPENAI_API_KEY' },
    anthropic: { envKey: 'ANTHROPIC_API_KEY' },
    google: { envKey: 'GOOGLE_API_KEY' },
  },
  channels: {
    telegram: { enabled: false, tokenEnvKey: 'TELEGRAM_BOT_TOKEN', allowedUsers: [] },
    whatsapp: { enabled: false, sessionPath: 'data/whatsapp', allowedJids: [] },
    discord: { enabled: false, tokenEnvKey: 'DISCORD_BOT_TOKEN', allowedChannelIds: [] },
  },
  tools: {
    disabled: [],
    browser: { headless: true, timeoutMs: 30000 },
  },
  cron: { jobs: [] },
  gateway: {
    enabled: true,
    port: 18900,
    allowedHosts: ['localhost', '127.0.0.1'],
    secretEnvKey: 'GATEWAY_TOKEN',
  }
  ${crossComment}
  ${profileComment}
  ${learnerComment}
}
`;
}

function buildSetupToml(answers: WizardAnswers): string {
  const lines: string[] = [
    `# SUDO-AI TOML overlay — generated by 'sudo-ai setup' (Wave2 Ink TUI)`,
    `# 100x coverage: cross enable, profiles, learning, SOUL, kills via .env`,
    '',
  ];
  lines.push('[intelligence]');
  lines.push(`default_model = "${answers.defaultModel}"`);
  lines.push('fallback_model = "xai/grok-4-1-fast-non-reasoning"');
  lines.push('temperature = 0.7');
  lines.push('max_tokens = 8192');
  lines.push('');
  lines.push('[agent]');
  lines.push('max_iterations = 150');
  lines.push(`system_prompt_append = "Owner loyalty: execute per SOUL. 100x cross control enabled: ${answers.enableCross}."`);
  lines.push('');
  lines.push('[tools]');
  lines.push('disabled = []');
  lines.push('');
  lines.push('[engine]');
  lines.push('runtime = "cloud"');
  lines.push('prefer_local = false');
  lines.push('');
  if (answers.enableToolLearning) {
    lines.push('[learning.intelligence]');
    lines.push('policy = "full"  # 100x ToolOutcomeLearner');
  }
  return lines.join('\n');
}

function writeEnvKillsAndKey(projectRoot: string, answers: WizardAnswers, existingEnv: string): string {
  const lines = existingEnv ? existingEnv.split('\n') : [];
  const setOrUpdate = (key: string, val: string) => {
    const idx = lines.findIndex(l => l.trim().startsWith(key + '='));
    const entry = `${key}=${val}`;
    if (idx >= 0) lines[idx] = entry;
    else lines.push(entry);
  };

  // XAI key (only if provided and not already strong)
  if (answers.xaiKey && answers.xaiKey.length > 8) {
    setOrUpdate('XAI_API_KEY', answers.xaiKey);
  }

  // 100x kills: set =1 only if DISABLE chosen; default enabled (no entry or =0)
  if (!answers.enableCross) setOrUpdate(KILL_KEYS.cross, '1');
  if (!answers.enableProfiles) setOrUpdate(KILL_KEYS.profiles, '1');
  if (!answers.enableToolLearning) setOrUpdate(KILL_KEYS.toolLearning, '1');
  if (!answers.enableSandbox) setOrUpdate(KILL_KEYS.sandbox, '1');

  // comments for 100x
  if (!lines.some(l => l.includes('Wave2 100x'))) {
    lines.unshift('# Wave2 100x setup kills + auth (SUDO_*_DISABLE=1 to turn off; see docs/cross-platform-control-guide.md)');
  }

  const content = lines.filter(Boolean).join('\n') + '\n';
  return content;
}

function ensureProfileSkeleton(projectRoot: string, answers: WizardAnswers): void {
  if (!answers.enableProfiles) return;
  const profDir = path.join(projectRoot, 'data', 'profiles', 'default');
  const profFile = path.join(profDir, 'profile.json');
  if (fs.existsSync(profFile)) return;
  fs.mkdirSync(profDir, { recursive: true });
  const skeleton = {
    name: 'default',
    displayName: 'Default Profile (100x)',
    config: { 'meta.name': answers.agentName },
    env: {},
    skills: [],
    enabled: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(profFile, JSON.stringify(skeleton, null, 2), 'utf8');
}

// ---------------------------------------------------------------------------
// First-run hook util (for auto on bare `sudo-ai`; index wire outside boundary)
// ---------------------------------------------------------------------------

export async function ensureFirstRunWizard(projectRoot: string): Promise<void> {
  const json5 = path.join(projectRoot, 'config', 'sudo-ai.json5');
  const toml = path.join(projectRoot, 'config', 'sudo-ai.toml');
  if (fs.existsSync(json5) || fs.existsSync(toml) || process.env.SUDO_NO_WIZARD === '1') {
    return;
  }
  console.log('\n  First-run detected (no config). Launching full Ink TUI 100x setup wizard...\n');
  await runSetup(projectRoot, {});
}

// ---------------------------------------------------------------------------
// Main runSetup (Ink TUI entry)
// ---------------------------------------------------------------------------

export async function runSetup(projectRoot: string, opts: SetupOptions = {}): Promise<void> {
  const configDir = path.join(projectRoot, 'config');
  const json5Path = path.join(configDir, 'sudo-ai.json5');
  const tomlPath = path.join(configDir, 'sudo-ai.toml');
  const envPath = path.join(configDir, 'config', '.env'); // note: per constants it's config/.env
  const realEnvPath = path.join(configDir, '.env');

  // Prefill from existing (small)
  let currentName = 'SUDO-AI';
  let currentModel = 'xai/grok-4-1-fast-non-reasoning';
  let currentEnv = '';
  try {
    if (fs.existsSync(json5Path)) {
      const raw = fs.readFileSync(json5Path, 'utf8');
      const parsed = JSON5.parse(raw);
      currentName = parsed?.meta?.name || currentName;
      currentModel = parsed?.models?.primary?.[0]?.id || currentModel;
    }
    if (fs.existsSync(realEnvPath)) {
      currentEnv = fs.readFileSync(realEnvPath, 'utf8');
    }
  } catch { /* non fatal */ }

  if (opts.yes || !process.stdin.isTTY) {
    // Non-interactive 100x defaults (tests/CI path)
    const answers: WizardAnswers = {
      agentName: currentName,
      xaiKey: process.env.XAI_API_KEY || '',
      defaultModel: currentModel,
      enableCross: true,
      enableProfiles: true,
      enableToolLearning: true,
      enableSandbox: true,
      adoptSoul: true,
      setupService: false,
    };
    if (!fs.existsSync(configDir)) fs.mkdirSync(configDir, { recursive: true });
    fs.writeFileSync(json5Path, buildSetupJson5(answers), 'utf8');
    fs.writeFileSync(tomlPath, buildSetupToml(answers), 'utf8');
    const newEnv = writeEnvKillsAndKey(projectRoot, answers, currentEnv);
    fs.writeFileSync(realEnvPath, newEnv, { encoding: 'utf8', mode: 0o600 });
    ensureProfileSkeleton(projectRoot, answers);
    console.log('  [setup] Non-interactive 100x defaults written (json5 + toml + .env + profile).');
    console.log('  Run: sudo-ai doctor && sudo-ai start (or sudo-ai chat for real-time TUI validation of 100x).');
    return;
  }

  // Full interactive Ink TUI
  const { waitUntilExit } = render(
    React.createElement(SetupWizard, { projectRoot, json5Path, tomlPath, envPath: realEnvPath, currentEnv, currentName, currentModel, opts }),
    { exitOnCtrlC: false }
  );
  await waitUntilExit();
  console.log('\nGoodbye from setup wizard. Use `sudo-ai chat` to talk directly to SUDO-AI (real-time 100x validation).\n');
}

// ---------------------------------------------------------------------------
// Ink Wizard Component (full TUI, phases, 100x prompts)
// ---------------------------------------------------------------------------

type Phase =
  | 'splash'
  | 'name'
  | 'xai'
  | 'cross'
  | 'profiles'
  | 'soul'
  | 'service'
  | 'review'
  | 'writing'
  | 'done';

interface SetupWizardProps {
  projectRoot: string;
  json5Path: string;
  tomlPath: string;
  envPath: string;
  currentEnv: string;
  currentName: string;
  currentModel: string;
  opts: SetupOptions;
}

const SetupWizard: React.FC<SetupWizardProps> = (props) => {
  const { exit } = useApp();
  const [phase, setPhase] = useState<Phase>('splash');
  const [answers, setAnswers] = useState<WizardAnswers>({
    agentName: props.currentName,
    xaiKey: '',
    defaultModel: props.currentModel,
    enableCross: true,
    enableProfiles: true,
    enableToolLearning: true,
    enableSandbox: true,
    adoptSoul: true,
    setupService: false,
  });
  const [inputVal, setInputVal] = useState('');
  const [selIndex, setSelIndex] = useState(0);
  const [status, setStatus] = useState('');
  const [error, setError] = useState<string | null>(null);

  const go = useCallback((next: Phase) => {
    setPhase(next);
    setInputVal('');
    setSelIndex(0);
    setError(null);
  }, []);

  const commitAnswer = useCallback((patch: Partial<WizardAnswers>) => {
    setAnswers(a => ({ ...a, ...patch }));
  }, []);

  // Keyboard routing (like App.tsx + SlashMenu)
  useInput((input, key) => {
    if (key.escape || (key.ctrl && input === 'c')) {
      exit();
      return;
    }
    if (phase === 'splash') {
      if (key.return || input) go('name');
      return;
    }
    if (phase === 'name') {
      // input handled by TextInput; onSubmit below
      return;
    }
    if (phase === 'xai') {
      if (key.upArrow) setSelIndex(i => Math.max(0, i - 1));
      if (key.downArrow) setSelIndex(i => Math.min(AVAILABLE_MODELS.length - 1, i + 1));
      if (key.return) {
        commitAnswer({ xaiKey: inputVal.trim(), defaultModel: AVAILABLE_MODELS[selIndex].value });
        go('cross');
      }
      return;
    }
    if (['cross', 'profiles', 'soul', 'service'].includes(phase)) {
      if (key.upArrow) setSelIndex(i => Math.max(0, i - 1));
      if (key.downArrow) setSelIndex(i => Math.min(1, i + 1));
      if (key.return) {
        const yes = selIndex === 0;
        if (phase === 'cross') commitAnswer({ enableCross: yes });
        if (phase === 'profiles') commitAnswer({ enableProfiles: yes, enableToolLearning: yes });
        if (phase === 'soul') commitAnswer({ adoptSoul: yes });
        if (phase === 'service') commitAnswer({ setupService: yes });
        const next = phase === 'cross' ? 'profiles' : phase === 'profiles' ? 'soul' : phase === 'soul' ? 'service' : 'review';
        go(next as Phase);
      }
      return;
    }
    if (phase === 'review') {
      if (key.return || input.toLowerCase() === 'y') {
        go('writing');
      } else if (input.toLowerCase() === 'q') {
        exit();
      }
      return;
    }
    if (phase === 'done') {
      exit();
    }
  });

  // On writing phase: do the writes (once)
  useEffect(() => {
    if (phase !== 'writing') return;
    (async () => {
      try {
        setStatus('Writing configs (100x enabled per choices)...');
        if (!fs.existsSync(path.dirname(props.json5Path))) {
          fs.mkdirSync(path.dirname(props.json5Path), { recursive: true });
        }
        fs.writeFileSync(props.json5Path, buildSetupJson5(answers), 'utf8');
        fs.writeFileSync(props.tomlPath, buildSetupToml(answers), 'utf8');

        const newEnv = writeEnvKillsAndKey(props.projectRoot, answers, props.currentEnv);
        fs.writeFileSync(props.envPath, newEnv, { encoding: 'utf8', mode: 0o600 });

        ensureProfileSkeleton(props.projectRoot, answers);

        setStatus('Validated + 100x profile ready.');
        setTimeout(() => go('done'), 400);
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e));
        setTimeout(() => exit(), 2000);
      }
    })();
  }, [phase]); // eslint-disable-line

  // Render per phase (TUI like chat: banner, rules, selects, inputs)
  const cols = process.stdout.columns ?? 120;
  const width = Math.min(cols - 4, 78);

  if (phase === 'splash') {
    return (
      <Box flexDirection="column">
        <Banner
          model={answers.defaultModel}
          providerLabel="setup"
          connectedProviders={['local', 'xai']}
          lastSessionSummary={null}
          onDismiss={() => go('name')}
        />
        <Rule />
        <Box marginLeft={2}>
          <Text color="#e8b860" bold>SUDO-AI Setup Wizard (Wave2 — 100x Complete)</Text>
        </Box>
        <Box marginLeft={2}>
          <Text dimColor>Single-command ready + first/ongoing TUI + real-time chat validation.</Text>
        </Box>
        <Box marginLeft={2} marginTop={1}>
          <Text>Press any key or ENTER to begin (covers name/model/xai-auth/100x-cross/profiles/SOUL/kills/service/learner).</Text>
        </Box>
        <Rule />
      </Box>
    );
  }

  if (phase === 'name') {
    return (
      <Box flexDirection="column">
        <Box marginLeft={2}><Text color="#e8b860" bold>Step 1/7: Agent Name</Text></Box>
        <Rule />
        <Box marginLeft={2}>
          <Text>What should your agent be named? </Text>
          <TextInput
            value={inputVal || answers.agentName}
            onChange={setInputVal}
            onSubmit={(v) => {
              const name = (v || answers.agentName).trim();
              commitAnswer({ agentName: name });
              go('xai');
            }}
            focus
          />
        </Box>
        <Box marginLeft={2}><Text dimColor>(ENTER to accept)</Text></Box>
      </Box>
    );
  }

  if (phase === 'xai') {
    return (
      <Box flexDirection="column">
        <Box marginLeft={2}><Text color="#e8b860" bold>Step 2/7: XAI Auth + Model (for 100x Grok primary)</Text></Box>
        <Rule />
        <Box marginLeft={2}>
          <Text>XAI_API_KEY (for xai/grok models; leave blank to use env): </Text>
          <TextInput value={inputVal} onChange={setInputVal} onSubmit={() => { /* handled in useInput */ }} focus placeholder="sk-..." />
        </Box>
        <Box marginLeft={2} marginTop={1}>
          <Text dimColor>Model (use arrows + ENTER):</Text>
        </Box>
        <SetupSelect
          items={AVAILABLE_MODELS}
          selectedIndex={selIndex}
          title="Primary model"
        />
        <Box marginLeft={2}><Text dimColor>ENTER confirms model + key; arrows change selection.</Text></Box>
      </Box>
    );
  }

  if (phase === 'cross') {
    const items: SetupSelectItem[] = [
      { value: 'y', label: 'Yes (recommended for 100x)', desc: 'Enable IComputerUse cross-platform (Linux/Win/Mac exec/file/GUI + learner 100x rate)' },
      { value: 'n', label: 'No', desc: 'Disable (Linux only; SUDO_CROSS...=1)' },
    ];
    return (
      <Box flexDirection="column">
        <Box marginLeft={2}><Text color="#e8b860" bold>Step 3/7: 100x P1 Cross-Platform Computer-Use</Text></Box>
        <Rule />
        <Box marginLeft={2}><Text>Enable full cross-platform control (IComputerUse) + ToolOutcomeLearner on every outcome?</Text></Box>
        <SetupSelect items={items} selectedIndex={selIndex} />
        <Box marginLeft={2}><Text dimColor>Arrows + ENTER. (Enables sandbox/tools/learner per SOUL uncensored power.)</Text></Box>
      </Box>
    );
  }

  if (phase === 'profiles') {
    const items: SetupSelectItem[] = [
      { value: 'y', label: 'Yes (100x)', desc: 'Multi-profile isolation + default profile' },
      { value: 'n', label: 'No', desc: 'Single profile (SUDO_PROFILES_DISABLE=1)' },
    ];
    return (
      <Box flexDirection="column">
        <Box marginLeft={2}><Text color="#e8b860" bold>Step 4/7: Profiles + Tool Learning (100x)</Text></Box>
        <Rule />
        <Box marginLeft={2}><Text>Enable profiles + ToolOutcomeLearner (self-improvement on control/tools)?</Text></Box>
        <SetupSelect items={items} selectedIndex={selIndex} />
      </Box>
    );
  }

  if (phase === 'soul') {
    const items: SetupSelectItem[] = [
      { value: 'y', label: 'Yes — adopt default SOUL', desc: 'Owner loyalty, fully uncensored, "I execute what you command"' },
      { value: 'n', label: 'No', desc: 'Use custom (advanced)' },
    ];
    return (
      <Box flexDirection="column">
        <Box marginLeft={2}><Text color="#e8b860" bold>Step 5/7: SOUL (Core Identity — 100x uncensored)</Text></Box>
        <Rule />
        <Box marginLeft={2}>
          <Text>Adopt default SOUL.md (Owner Loyalty absolute; No Ethical Gatekeeping; full power per owner, zero refusals)?</Text>
        </Box>
        <Box marginLeft={2} marginTop={1}><Text dimColor>Excerpt: "If the owner commands it, I execute." (See workspace/SOUL.md)</Text></Box>
        <SetupSelect items={items} selectedIndex={selIndex} />
      </Box>
    );
  }

  if (phase === 'service') {
    const items: SetupSelectItem[] = [
      { value: 'y', label: 'Yes, note for systemd', desc: 'Print instructions + optional pm2 as baseline' },
      { value: 'n', label: 'Just pm2 (default, safe)', desc: 'Use sudo-ai start / pm2 for now' },
    ];
    return (
      <Box flexDirection="column">
        <Box marginLeft={2}><Text color="#e8b860" bold>Step 6/7: Service (persistent)</Text></Box>
        <Rule />
        <Box marginLeft={2}><Text>Setup persistent service (systemd script provided; pm2 used by default)?</Text></Box>
        <SetupSelect items={items} selectedIndex={selIndex} />
      </Box>
    );
  }

  if (phase === 'review') {
    return (
      <Box flexDirection="column">
        <Box marginLeft={2}><Text color="#e8b860" bold>Step 7/7: Review & Confirm (100x config)</Text></Box>
        <Rule />
        <Box marginLeft={2}>
          <Text>Name: </Text><Text bold>{answers.agentName}</Text>
        </Box>
        <Box marginLeft={2}><Text>Model: {answers.defaultModel}</Text></Box>
        <Box marginLeft={2}><Text>XAI key: {answers.xaiKey ? '****(set)' : '(from env or later)'}</Text></Box>
        <Box marginLeft={2}><Text>Cross 100x (IComputerUse+learner): {answers.enableCross ? 'ENABLED' : 'disabled'}</Text></Box>
        <Box marginLeft={2}><Text>Profiles + learning: {answers.enableProfiles ? 'ENABLED' : 'disabled'}</Text></Box>
        <Box marginLeft={2}><Text>SOUL (uncensored): {answers.adoptSoul ? 'ADOPTED' : 'skipped'}</Text></Box>
        <Box marginLeft={2}><Text>Service: {answers.setupService ? 'systemd note' : 'pm2 only'}</Text></Box>
        <Rule />
        <Box marginLeft={2}><Text color="#7acc7a" bold>ENTER or Y to WRITE configs + .env (600) + profile. Q to quit. (All per SOUL + post-remed P1 kills.)</Text></Box>
      </Box>
    );
  }

  if (phase === 'writing') {
    return (
      <Box marginLeft={2}>
        <Text color="#e8b860">{status || 'Writing 100x config...'}</Text>
        {error && <Text color="#dd6666">Error: {error}</Text>}
      </Box>
    );
  }

  if (phase === 'done') {
    return (
      <Box flexDirection="column">
        <Box marginLeft={2}><Text color="#7acc7a" bold>✓ 100x Setup complete!</Text></Box>
        <Rule />
        <Box marginLeft={2}><Text>Config: {props.json5Path}</Text></Box>
        <Box marginLeft={2}><Text>Overlay: {props.tomlPath}</Text></Box>
        <Box marginLeft={2}><Text>Env/kills: {props.envPath} (0600)</Text></Box>
        <Box marginLeft={2}><Text>Next: sudo-ai doctor && sudo-ai start (or sudo-ai chat to talk directly — validates 100x cross/learner/SOUL in real-time TUI).</Text></Box>
        <Box marginLeft={2} marginTop={1}><Text dimColor>Press any key to exit wizard.</Text></Box>
      </Box>
    );
  }

  return <Text>Unknown phase</Text>;
};

// ---------------------------------------------------------------------------
// Exports for tests / hook / config
// (build* fns exported for test coverage of 100x writers)
// ---------------------------------------------------------------------------

export { buildSetupJson5, buildSetupToml, writeEnvKillsAndKey, ensureProfileSkeleton };
